version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"   # location of your pyproject.toml
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:59"  # UTC
    open-pull-requests-limit: 1
    groups:
      all-deps:
        patterns:
          - "*"
